# 基础

## 函数参数

+ 2个参数: `req` `req`

+ 3个参数: `req` `res` `next`

+ 4个参数: `err` `req` `res` `next`

## 概述

+ 当匹配到了请求后交给第一个处理函数处理

+ 函数中需要手动的交给后续中间件处理 `next()`

  ```js
  app.get('/abc', (req, res, next) => {
    console.log(1111);
    next();
  }, (req, res, next) => {
    console.log(222);
    next()
  })
  ```

## 中间件处理细节

+ 如果后续已经没有了中间件

  + express 发现如果响应没有结束，会 **响应 404**

+ 如果中间件发生了错误

  + 不会停止服务器

  + 相当于调用了 `next(错误对象)` `next(new Error('错误提示'))`

  + 寻找后续的错误处理中间件 -+ 如果没有则 **响应500**

  ```js
  app.get('/abc', (req, res, next) => {
    console.log(1111);
    next();
  }, (req, res, next) => {
    console.log(222);
    next()
  })

  app.get('/abc', (req, res, next) => {
    console.log(333);
    throw new Error('辣鸡')
    next();

  }, (req, res, next) => {
    console.log(444);
    next()
  })
  ```

## 响应错误的中间件

+ 函数需要4个参数

  ```js
  /**
  * errorMiddleware.js
  * 处理错误的中间件
  */
  module.exports = (err, req, res, next) => {

    // 发生了错误
    if(err) {
      const errObj = {
        code: 500,
        msg: err instanceof Error ? err.message : err
      }
      res.status(500).send(errObj);
      return;
    }
    next();
  };
  ```

  ```js
  // 使用
  const errorMiddleware = require('./errorMiddleware');

  app.use('/abc', (req, res, next) => {
    console.log(111);
    next();
  },(req, res, next) => {
    console.log(222);
    next();
  }, errorMiddleware);
  ```

## 处理示意图

![中间件示意图](./../images/中间件示意图.jpg)
